# Generated by Django 3.1.7 on 2021-03-12 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('max_sis_if', '0002_auto_20210312_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setor',
            name='nome',
            field=models.SlugField(blank=True, max_length=10, null=True, verbose_name='Nome Setor'),
        ),
        migrations.AlterField(
            model_name='setor',
            name='sigla',
            field=models.SlugField(max_length=10, verbose_name='Sigla'),
        ),
    ]
