# Generated by Django 3.1.7 on 2021-03-13 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('max_sis_if', '0003_auto_20210312_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteminventario',
            name='data_conferencia',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Data Últ. Conferência'),
        ),
    ]
