# Generated by Django 3.1.7 on 2021-03-21 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('max_sis_if', '0004_auto_20210313_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteminventario',
            name='dependencia_atual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dependencia_atual', to='max_sis_if.dependencia', verbose_name='Dependência Importada'),
        ),
        migrations.AlterField(
            model_name='iteminventario',
            name='setor_atual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setor_atual', to='max_sis_if.setor', verbose_name='Setor Importado'),
        ),
    ]
