# Generated by Django 3.1.7 on 2021-03-09 23:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.SlugField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='ItemInventario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tombo', models.IntegerField()),
                ('descricao', models.TextField()),
                ('valor', models.DecimalField(decimal_places=3, max_digits=5, verbose_name='Valor R$')),
                ('conta_contabil', models.DecimalField(decimal_places=3, max_digits=5, verbose_name='Conta contábil')),
                ('empenho', models.IntegerField()),
                ('fornecedor', models.CharField(max_length=18)),
                ('numero_documento', models.IntegerField()),
                ('data_aquisicao', models.DateField()),
                ('data_ateste', models.DateField()),
                ('dependencia', models.CharField(max_length=255)),
                ('responsavel', models.CharField(max_length=255)),
                ('data_importacao', models.DateTimeField(auto_now_add=True)),
                ('item_conferido', models.BooleanField()),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario_app.setor')),
                ('usuario_conferencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
