# Generated by Django 3.1.7 on 2021-03-11 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventario_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dependencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('observacao', models.TextField(null=True, verbose_name='Observação')),
            ],
        ),
        migrations.AddField(
            model_name='iteminventario',
            name='observacao',
            field=models.TextField(null=True, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='iteminventario',
            name='data_aquisicao',
            field=models.DateField(verbose_name='Data Aquisição'),
        ),
        migrations.AlterField(
            model_name='iteminventario',
            name='data_ateste',
            field=models.DateField(verbose_name='Data Ateste'),
        ),
        migrations.AlterField(
            model_name='iteminventario',
            name='data_importacao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data Importação'),
        ),
        migrations.AlterField(
            model_name='iteminventario',
            name='dependencia',
            field=models.CharField(max_length=255, null=True, verbose_name='Dependência'),
        ),
        migrations.AlterField(
            model_name='iteminventario',
            name='descricao',
            field=models.TextField(verbose_name='descrição'),
        ),
        migrations.AlterField(
            model_name='iteminventario',
            name='empenho',
            field=models.IntegerField(verbose_name='Empenho'),
        ),
        migrations.AlterField(
            model_name='iteminventario',
            name='fornecedor',
            field=models.CharField(max_length=18, verbose_name='Fornecedor'),
        ),
        migrations.AlterField(
            model_name='iteminventario',
            name='item_conferido',
            field=models.BooleanField(null=True, verbose_name='Item Conferido?'),
        ),
        migrations.AlterField(
            model_name='iteminventario',
            name='numero_documento',
            field=models.IntegerField(verbose_name='Nº Documento'),
        ),
        migrations.AlterField(
            model_name='iteminventario',
            name='responsavel',
            field=models.CharField(max_length=255, verbose_name='responsável'),
        ),
        migrations.AlterField(
            model_name='iteminventario',
            name='tombo',
            field=models.IntegerField(verbose_name='Tombo'),
        ),
        migrations.AlterField(
            model_name='iteminventario',
            name='usuario_conferencia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
