# Generated by Django 3.1.7 on 2021-03-11 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventario_app', '0002_auto_20210311_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteminventario',
            name='dependencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario_app.dependencia', verbose_name='Dependência'),
        ),
        migrations.AlterField(
            model_name='iteminventario',
            name='observacao',
            field=models.TextField(blank=True, null=True, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='iteminventario',
            name='usuario_conferencia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário Conferência'),
        ),
    ]
