# Generated by Django 3.1.7 on 2021-03-11 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_app', '0004_auto_20210311_0957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dependencia',
            old_name='nome',
            new_name='nome_dependencia',
        ),
    ]
