# Generated by Django 3.1.7 on 2021-03-11 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_app', '0005_auto_20210311_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='setor',
            name='nome',
            field=models.SlugField(blank=True, max_length=7, null=True, verbose_name='Nome Setor'),
        ),
        migrations.AddField(
            model_name='setor',
            name='observacao',
            field=models.TextField(blank=True, null=True, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='dependencia',
            name='nome_dependencia',
            field=models.CharField(max_length=255, verbose_name='Nome da Dependência'),
        ),
        migrations.AlterField(
            model_name='dependencia',
            name='observacao',
            field=models.TextField(blank=True, null=True, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='setor',
            name='sigla',
            field=models.SlugField(max_length=7, verbose_name='Sigla'),
        ),
    ]
