# Generated by Django 3.1.7 on 2021-03-11 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_app', '0008_auto_20210311_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iteminventario',
            name='setor',
        ),
        migrations.AddField(
            model_name='iteminventario',
            name='setor_atual',
            field=models.CharField(max_length=255, null=True, verbose_name='responsável'),
        ),
        migrations.AddField(
            model_name='iteminventario',
            name='setor_conferencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario_app.setor'),
        ),
    ]
