# Generated by Django 3.1.7 on 2021-03-11 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_app', '0009_auto_20210311_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteminventario',
            name='setor_atual',
            field=models.CharField(max_length=255, null=True, verbose_name='Setor Atual'),
        ),
        migrations.AlterField(
            model_name='iteminventario',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True, verbose_name='Valor R$'),
        ),
    ]
