# Generated by Django 3.1.7 on 2021-03-11 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_app', '0010_auto_20210311_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iteminventario',
            name='dependencia',
        ),
        migrations.AddField(
            model_name='iteminventario',
            name='dependencia_atual',
            field=models.CharField(max_length=255, null=True, verbose_name='Dependência'),
        ),
        migrations.AddField(
            model_name='iteminventario',
            name='dependencia_conferencia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario_app.dependencia', verbose_name='Dependência Conferência'),
        ),
        migrations.AlterField(
            model_name='iteminventario',
            name='setor_conferencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario_app.setor', verbose_name='Setor Conferência'),
        ),
    ]
