# Generated by Django 3.1.7 on 2021-03-11 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_app', '0011_auto_20210311_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteminventario',
            name='dependencia_atual',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dependencia_atual', to='inventario_app.dependencia', verbose_name='Dependência Atual'),
        ),
        migrations.AlterField(
            model_name='iteminventario',
            name='dependencia_conferencia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dependencia_conferencia', to='inventario_app.dependencia', verbose_name='Dependência Conferência'),
        ),
        migrations.AlterField(
            model_name='iteminventario',
            name='setor_atual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setor_atual', to='inventario_app.setor', verbose_name='Setor Atual'),
        ),
        migrations.AlterField(
            model_name='iteminventario',
            name='setor_conferencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setor_conferencia', to='inventario_app.setor', verbose_name='Setor Conferência'),
        ),
    ]
