# Generated by Django 3.1.7 on 2021-03-11 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_app', '0012_auto_20210311_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteminventario',
            name='conta_contabil',
            field=models.IntegerField(null=True, verbose_name='Conta contábil'),
        ),
    ]
