# Generated by Django 3.1.7 on 2021-03-11 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_app', '0013_auto_20210311_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='iteminventario',
            name='data_conferencia',
            field=models.DateTimeField(auto_now=True, verbose_name='Data Importação'),
        ),
        migrations.AlterField(
            model_name='iteminventario',
            name='data_importacao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data Importação/Criação'),
        ),
        migrations.AlterField(
            model_name='iteminventario',
            name='dependencia_atual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dependencia_atual', to='inventario_app.dependencia', verbose_name='Dependência Atual'),
        ),
        migrations.AlterField(
            model_name='iteminventario',
            name='dependencia_conferencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dependencia_conferencia', to='inventario_app.dependencia', verbose_name='Dependência Conferência'),
        ),
    ]
