# Generated by Django 3.1.7 on 2021-03-12 02:24

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_app', '0014_auto_20210311_1954'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dependencia',
            options={'verbose_name': 'Dependência', 'verbose_name_plural': 'Dependências'},
        ),
        migrations.AlterModelOptions(
            name='iteminventario',
            options={'verbose_name': 'Item do Inventário', 'verbose_name_plural': 'Itens do Inventário'},
        ),
        migrations.AlterModelOptions(
            name='setor',
            options={'verbose_name': 'Setor', 'verbose_name_plural': 'Setores'},
        ),
        migrations.AddField(
            model_name='dependencia',
            name='descricao_local',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Descrição do Local'),
        ),
        migrations.AlterField(
            model_name='iteminventario',
            name='data_conferencia',
            field=models.DateTimeField(auto_now=True, verbose_name='Data Últ. Conferência'),
        ),
        migrations.AlterField(
            model_name='setor',
            name='observacao',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Observação'),
        ),
    ]
