# Generated by Django 3.1.7 on 2021-03-12 03:25

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_app', '0015_auto_20210311_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependencia',
            name='observacao',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='iteminventario',
            name='observacao',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Observação'),
        ),
    ]
